### ISSUE TITLE
Armor set doesn't seem to be recognized

### ISSUE THREAD

**Issue by Vampsku11** [hallis21/ArmorSetEffects#1]
MC 1.14.4
server is paper-173.jar
only plugin in plugins folder is ArmorSetBonus-2.1.1.jar

Armor Set Effects is not working for me, I have the commands but armor sets do not appear to be registering. I included it in several mods when first starting the server. When I found a test armor set I had written did not seem to work, I removed all plugins except this, deleted files from armorSets folder, and copied example_set.yml to armorSets folder and restarted server.

During startup I find these messages matching armor:
[20:11:31 INFO]: [ArmorSetBonus] Loading ArmorSetBonus v2.0
[20:11:47 INFO]: [ArmorSetBonus] Enabling ArmorSetBonus v2.0
[20:11:47 INFO]: [ArmorSetBonus] Found folder, reading sets.

When I issue the commands this is all I get in the console:
[20:14:49 INFO]: Vampskull issued server command: /armor-list
[20:14:54 INFO]: Vampskull issued server command: /armor-reload
[20:14:54 INFO]: [ArmorSetBonus] Found folder, reading sets.
>

**Comment by hallis21** [comment]
Are you sure that the files armorset files are placed in the right folder? Sets should be placed in plugin/ArmorSetEffects/armorSets. I will be updating the plugin on spigot and bukkit with a new version that gives an error if no files are detected. i have also added feedback for /armor-list when there are no sets loaded.

GitHub version should be updated as of right now, you can build it using maven with "clean package install" or just get the new files from spigot/bukkit.

**Comment by Vampsku11** [comment]
Seems like this issue was closed before resolution.

Yes, as explained I copied example_set.yml to armorSets folder. When the folder is empty I get a seperate error that no files were found.

I was using version 2.1.1 from dev.bukkit.org, but I have deleted and now have downloaded the 2.1.1 version just published to spigot.org. Are these different? I deleted ArmorSetEffects/, restarted server, stopped server, and copied the example_set.yml file to armorSets/ folder again. That command looks like this:

plugins/ArmorSetBonus$ sudo cp example_set.yml armorSets/example_set.yml

Now I am getting the error that there are no files in the folder, which is new.
[09:15:28 INFO]: No Files found in folder ArmorSetEffects/ArmorSets
I noticed the folder here is using different capitalization, so I copied the armorSets/ folder to ArmorSets/ and restarted, but getting same error.

So I have changed to version 2.1 from the spigot site and am getting the same results as version 2.1.1 from the bukkit site. "Found folder, reading sets" but no sets listed for command /armor-list.

**Comment by hallis21** [comment]
In the newly updated version I simply added pointers for when no files were detected in "ArmorSetBonus/armorSets". 
This one: [09:15:28 INFO]: No Files found in folder ArmorSetEffects/ArmorSets
As well as a respons when there are no sets to list.

Capital letters are ignored by the reader, so it's not the folder. As long as the name is correct and placed like this in the server folder everything should work.
"\plugins\ArmorSetBonus\ArmorSets\example_set.yml"

I notice you are using linux, although I can't find any threads about this, I will have to test it later today on a linux server.

**Comment by hallis21** [comment]
Problem solved in newest version, problem was in usage on linux systems. File iteration of directory method was deprecated on linux.
